[
  { token: 'EOL', line: 1, column: 1 },
  { token: 'EOL', line: 2, column: 1 },
  { token: '.', line: 3, column: 1 },
  { token: 'identifier', string: 'define', line: 3, column: 2 },
  { token: 'identifier', string: 'gtoe', line: 3, column: 9 },
  { token: 'signal', string: '≥', line: 3, column: 14 },
  { token: 'EOL', line: 3, column: 17 },
  { token: '.', line: 4, column: 1 },
  { token: 'identifier', string: 'define', line: 4, column: 2 },
  { token: 'identifier', string: 'ne', line: 4, column: 9 },
  { token: 'signal', string: '≠', line: 4, column: 12 },
  { token: 'EOL', line: 4, column: 15 },
  { token: '.', line: 5, column: 1 },
  { token: 'identifier', string: 'define', line: 5, column: 2 },
  { token: 'identifier', string: 'ltoe', line: 5, column: 9 },
  { token: 'signal', string: '≤', line: 5, column: 14 },
  { token: 'EOL', line: 5, column: 17 },
  { token: 'EOL', line: 6, column: 1 },
  { token: '.', line: 7, column: 1 },
  { token: 'identifier', string: 'define', line: 7, column: 2 },
  { token: 'identifier', string: 'clear', line: 7, column: 9 },
  { token: 'signal', string: 'white', line: 7, column: 15 },
  { token: 'number', string: '1', number: 1, line: 7, column: 23 },
  { token: 'EOL', line: 7, column: 24 },
  { token: 'EOL', line: 8, column: 1 },
  { token: '.', line: 9, column: 1 },
  { token: 'identifier', string: 'global', line: 9, column: 2 },
  { token: 'identifier', string: 'sp', line: 9, column: 9 },
  { token: 'EOL', line: 9, column: 11 },
  { token: '.', line: 10, column: 1 },
  { token: 'identifier', string: 'global', line: 10, column: 2 },
  { token: 'identifier', string: 'stack', line: 10, column: 9 },
  { token: 'number', string: '20', number: 20, line: 10, column: 15 },
  { token: 'EOL', line: 10, column: 17 },
  { token: 'EOL', line: 11, column: 1 },
  { token: '.', line: 12, column: 1 },
  { token: 'identifier', string: 'define', line: 12, column: 2 },
  { token: 'identifier', string: 'ic', line: 12, column: 9 },
  { token: 'number', string: '5', number: 5, line: 12, column: 12 },
  { token: 'EOL', line: 12, column: 13 },
  { token: '.', line: 13, column: 1 },
  { token: 'identifier', string: 'define', line: 13, column: 2 },
  { token: 'identifier', string: 'mc', line: 13, column: 9 },
  { token: 'number', string: '1', number: 1, line: 13, column: 12 },
  { token: 'EOL', line: 13, column: 13 },
  { token: 'EOL', line: 14, column: 1 },
  { token: '%', line: 15, column: 1 },
  { token: 'identifier', string: 'macro', line: 15, column: 2 },
  { token: 'identifier', string: 'stop', line: 15, column: 8 },
  { token: 'EOL', line: 15, column: 12 },
  { token: 'identifier', string: 'none', line: 16, column: 3 },
  { token: 'signal', string: 'B', line: 16, column: 11 },
  { token: 'number', string: '1', number: 1, line: 16, column: 15 },
  { token: ',', line: 16, column: 16 },
  { token: 'signal', string: 'jump', line: 16, column: 18 },
  { token: 'EOL', line: 16, column: 24 },
  { token: 'identifier', string: 'none', line: 17, column: 3 },
  { token: 'signal', string: 'B', line: 17, column: 11 },
  { token: 'number', string: '1', number: 1, line: 17, column: 15 },
  { token: ',', line: 17, column: 16 },
  { token: 'signal', string: 'jump', line: 17, column: 18 },
  { token: 'EOL', line: 17, column: 24 },
  { token: 'identifier', string: 'none', line: 18, column: 3 },
  { token: 'signal', string: 'B', line: 18, column: 11 },
  { token: 'number', string: '1', number: 1, line: 18, column: 15 },
  { token: ',', line: 18, column: 16 },
  { token: 'signal', string: 'jump', line: 18, column: 18 },
  { token: 'EOL', line: 18, column: 24 },
  { token: '%', line: 19, column: 1 },
  { token: 'identifier', string: 'endmacro', line: 19, column: 2 },
  { token: 'EOL', line: 19, column: 10 },
  { token: 'EOL', line: 20, column: 1 },
  { token: '%', line: 21, column: 1 },
  { token: 'identifier', string: 'macro', line: 21, column: 2 },
  { token: 'identifier', string: 'mov', line: 21, column: 8 },
  { token: 'EOL', line: 21, column: 29 },
  { token: 'identifier', string: 'none', line: 22, column: 3 },
  { token: 'identifier', string: 'clear', line: 22, column: 11 },
  { token: ',', line: 22, column: 16 },
  { token: ':', line: 22, column: 18 },
  { token: 'number', string: '1', number: 1, line: 22, column: 19 },
  { token: 'EOL', line: 22, column: 20 },
  { token: 'identifier', string: 'connect', line: 23, column: 3 },
  { token: ':', line: 23, column: 11 },
  { token: 'number', string: '0', number: 0, line: 23, column: 12 },
  { token: ',', line: 23, column: 13 },
  { token: ':', line: 23, column: 15 },
  { token: 'number', string: '1', number: 1, line: 23, column: 16 },
  { token: ',', line: 23, column: 17 },
  { token: ':', line: 23, column: 19 },
  { token: 'number', string: '2', number: 2, line: 23, column: 20 },
  { token: 'EOL', line: 23, column: 21 },
  { token: '%', line: 24, column: 1 },
  { token: 'identifier', string: 'endmacro', line: 24, column: 2 },
  { token: 'EOL', line: 24, column: 10 },
  { token: 'EOL', line: 25, column: 1 },
  { token: '%', line: 26, column: 1 },
  { token: 'identifier', string: 'macro', line: 26, column: 2 },
  { token: 'identifier', string: 'set', line: 26, column: 8 },
  { token: 'EOL', line: 26, column: 24 },
  { token: 'identifier', string: 'none', line: 27, column: 3 },
  { token: 'identifier', string: 'clear', line: 27, column: 11 },
  { token: ',', line: 27, column: 16 },
  { token: ':', line: 27, column: 18 },
  { token: 'number', string: '1', number: 1, line: 27, column: 19 },
  { token: 'EOL', line: 27, column: 20 },
  { token: 'identifier', string: 'none', line: 28, column: 3 },
  { token: ':', line: 28, column: 11 },
  { token: 'number', string: '0', number: 0, line: 28, column: 12 },
  { token: ',', line: 28, column: 13 },
  { token: ':', line: 28, column: 15 },
  { token: 'number', string: '1', number: 1, line: 28, column: 16 },
  { token: 'EOL', line: 28, column: 17 },
  { token: '%', line: 29, column: 1 },
  { token: 'identifier', string: 'endmacro', line: 29, column: 2 },
  { token: 'EOL', line: 29, column: 10 },
  { token: 'EOL', line: 30, column: 1 },
  { token: '%', line: 31, column: 1 },
  { token: 'identifier', string: 'macro', line: 31, column: 2 },
  { token: 'identifier', string: 'jmp', line: 31, column: 8 },
  { token: 'EOL', line: 31, column: 19 },
  { token: 'identifier', string: 'none', line: 32, column: 3 },
  { token: 'signal', string: 'B', line: 32, column: 11 },
  { token: 'identifier', string: 'ip', line: 32, column: 15 },
  { token: '+', line: 32, column: 18 },
  { token: 'number', string: '3', number: 3, line: 32, column: 20 },
  { token: '-', line: 32, column: 22 },
  { token: ':', line: 32, column: 24 },
  { token: 'number', string: '0', number: 0, line: 32, column: 25 },
  { token: ',', line: 32, column: 26 },
  { token: 'signal', string: 'jump', line: 32, column: 28 },
  { token: 'EOL', line: 32, column: 34 },
  { token: 'identifier', string: 'nop', line: 33, column: 3 },
  { token: 'EOL', line: 33, column: 6 },
  { token: 'identifier', string: 'nop', line: 34, column: 3 },
  { token: 'EOL', line: 34, column: 6 },
  { token: '%', line: 35, column: 1 },
  { token: 'identifier', string: 'endmacro', line: 35, column: 2 },
  { token: 'EOL', line: 35, column: 10 },
  { token: 'EOL', line: 36, column: 1 },
  { token: '%', line: 37, column: 1 },
  { token: 'identifier', string: 'macro', line: 37, column: 2 },
  { token: 'identifier', string: 'branch', line: 37, column: 8 },
  { token: 'EOL', line: 37, column: 91 },
  { token: 'identifier', string: 'decid', line: 38, column: 3 },
  { token: ':', line: 38, column: 11 },
  { token: 'number', string: '1', number: 1, line: 38, column: 12 },
  { token: ',', line: 38, column: 13 },
  { token: ':', line: 38, column: 15 },
  { token: 'number', string: '2', number: 2, line: 38, column: 16 },
  { token: ',', line: 38, column: 17 },
  { token: ':', line: 38, column: 19 },
  { token: 'number', string: '3', number: 3, line: 38, column: 20 },
  { token: ',', line: 38, column: 21 },
  { token: 'signal', string: 'B', line: 38, column: 23 },
  { token: ',', line: 38, column: 26 },
  { token: ',', line: 38, column: 27 },
  { token: ':', line: 38, column: 29 },
  { token: 'number', string: '4', number: 4, line: 38, column: 30 },
  { token: ',', line: 38, column: 31 },
  { token: 'signal', string: 'jump', line: 38, column: 33 },
  { token: ',', line: 38, column: 39 },
  { token: 'signal', string: 'B', line: 38, column: 41 },
  { token: 'identifier', string: 'ip', line: 38, column: 45 },
  { token: '+', line: 38, column: 48 },
  { token: 'number', string: '3', number: 3, line: 38, column: 50 },
  { token: '-', line: 38, column: 52 },
  { token: ':', line: 38, column: 54 },
  { token: 'number', string: '0', number: 0, line: 38, column: 55 },
  { token: 'EOL', line: 38, column: 56 },
  { token: 'identifier', string: 'nop', line: 39, column: 3 },
  { token: 'EOL', line: 39, column: 6 },
  { token: 'identifier', string: 'nop', line: 40, column: 3 },
  { token: 'EOL', line: 40, column: 6 },
  { token: '%', line: 41, column: 1 },
  { token: 'identifier', string: 'endmacro', line: 41, column: 2 },
  { token: 'EOL', line: 41, column: 10 },
  { token: 'EOL', line: 42, column: 1 },
  { token: '%', line: 43, column: 1 },
  { token: 'identifier', string: 'macro', line: 43, column: 2 },
  { token: 'identifier', string: 'wait', line: 43, column: 8 },
  { token: 'EOL', line: 43, column: 82 },
  { token: 'identifier', string: 'decid', line: 44, column: 3 },
  { token: ':', line: 44, column: 11 },
  { token: 'number', string: '0', number: 0, line: 44, column: 12 },
  { token: ',', line: 44, column: 13 },
  { token: ':', line: 44, column: 15 },
  { token: 'number', string: '1', number: 1, line: 44, column: 16 },
  { token: ',', line: 44, column: 17 },
  { token: ':', line: 44, column: 19 },
  { token: 'number', string: '2', number: 2, line: 44, column: 20 },
  { token: ',', line: 44, column: 21 },
  { token: 'signal', string: 'B', line: 44, column: 23 },
  { token: 'number', string: '1', number: 1, line: 44, column: 27 },
  { token: ',', line: 44, column: 28 },
  { token: ',', line: 44, column: 29 },
  { token: ':', line: 44, column: 31 },
  { token: 'number', string: '3', number: 3, line: 44, column: 32 },
  { token: ',', line: 44, column: 33 },
  { token: 'signal', string: 'jump', line: 44, column: 35 },
  { token: 'EOL', line: 44, column: 41 },
  { token: 'identifier', string: 'decid', line: 45, column: 3 },
  { token: ':', line: 45, column: 11 },
  { token: 'number', string: '0', number: 0, line: 45, column: 12 },
  { token: ',', line: 45, column: 13 },
  { token: ':', line: 45, column: 15 },
  { token: 'number', string: '1', number: 1, line: 45, column: 16 },
  { token: ',', line: 45, column: 17 },
  { token: ':', line: 45, column: 19 },
  { token: 'number', string: '2', number: 2, line: 45, column: 20 },
  { token: ',', line: 45, column: 21 },
  { token: 'signal', string: 'B', line: 45, column: 23 },
  { token: 'number', string: '1', number: 1, line: 45, column: 27 },
  { token: ',', line: 45, column: 28 },
  { token: ',', line: 45, column: 29 },
  { token: ':', line: 45, column: 31 },
  { token: 'number', string: '3', number: 3, line: 45, column: 32 },
  { token: ',', line: 45, column: 33 },
  { token: 'signal', string: 'jump', line: 45, column: 35 },
  { token: 'EOL', line: 45, column: 41 },
  { token: 'identifier', string: 'decid', line: 46, column: 3 },
  { token: ':', line: 46, column: 11 },
  { token: 'number', string: '0', number: 0, line: 46, column: 12 },
  { token: ',', line: 46, column: 13 },
  { token: ':', line: 46, column: 15 },
  { token: 'number', string: '1', number: 1, line: 46, column: 16 },
  { token: ',', line: 46, column: 17 },
  { token: ':', line: 46, column: 19 },
  { token: 'number', string: '2', number: 2, line: 46, column: 20 },
  { token: ',', line: 46, column: 21 },
  { token: 'signal', string: 'B', line: 46, column: 23 },
  { token: 'number', string: '1', number: 1, line: 46, column: 27 },
  { token: ',', line: 46, column: 28 },
  { token: ',', line: 46, column: 29 },
  { token: ':', line: 46, column: 31 },
  { token: 'number', string: '3', number: 3, line: 46, column: 32 },
  { token: ',', line: 46, column: 33 },
  { token: 'signal', string: 'jump', line: 46, column: 35 },
  { token: 'EOL', line: 46, column: 41 },
  { token: '%', line: 47, column: 1 },
  { token: 'identifier', string: 'endmacro', line: 47, column: 2 },
  { token: 'EOL', line: 47, column: 10 },
  { token: 'EOL', line: 48, column: 1 },
  { token: '%', line: 49, column: 1 },
  { token: 'identifier', string: 'macro', line: 49, column: 2 },
  { token: 'identifier', string: 'connect', line: 49, column: 8 },
  { token: 'EOL', line: 49, column: 52 },
  { token: 'identifier', string: 'arith', line: 50, column: 3 },
  { token: 'signal', string: 'each', line: 50, column: 11 },
  { token: ',', line: 50, column: 17 },
  { token: 'signal', string: 'OR', line: 50, column: 19 },
  { token: ',', line: 50, column: 23 },
  { token: 'number', string: '0', number: 0, line: 50, column: 25 },
  { token: ',', line: 50, column: 26 },
  { token: 'signal', string: 'each', line: 50, column: 28 },
  { token: ',', line: 50, column: 34 },
  { token: ':', line: 50, column: 36 },
  { token: 'number', string: '2', number: 2, line: 50, column: 37 },
  { token: ',', line: 50, column: 38 },
  { token: ':', line: 50, column: 40 },
  { token: 'number', string: '0', number: 0, line: 50, column: 41 },
  { token: ',', line: 50, column: 42 },
  { token: ':', line: 50, column: 44 },
  { token: 'number', string: '1', number: 1, line: 50, column: 45 },
  { token: 'EOL', line: 50, column: 46 },
  { token: '%', line: 51, column: 1 },
  { token: 'identifier', string: 'endmacro', line: 51, column: 2 },
  { token: 'EOL', line: 51, column: 10 },
  { token: 'EOL', line: 52, column: 1 },
  { token: '%', line: 53, column: 1 },
  { token: 'identifier', string: 'macro', line: 53, column: 2 },
  { token: 'identifier', string: 'load', line: 53, column: 8 },
  { token: 'EOL', line: 53, column: 44 },
  { token: 'identifier', string: 'none', line: 54, column: 3 },
  { token: 'signal', string: 'green', line: 54, column: 11 },
  { token: ':', line: 54, column: 19 },
  { token: 'number', string: '0', number: 0, line: 54, column: 20 },
  { token: ',', line: 54, column: 21 },
  { token: 'signal', string: 'memq', line: 54, column: 23 },
  { token: 'EOL', line: 54, column: 29 },
  { token: 'identifier', string: 'nop', line: 55, column: 3 },
  { token: 'EOL', line: 55, column: 6 },
  { token: 'identifier', string: 'nop', line: 56, column: 3 },
  { token: 'EOL', line: 56, column: 6 },
  { token: 'identifier', string: 'connect', line: 57, column: 3 },
  { token: 'signal', string: 'memr', line: 57, column: 11 },
  { token: ',', line: 57, column: 17 },
  { token: ':', line: 57, column: 19 },
  { token: 'number', string: '1', number: 1, line: 57, column: 20 },
  { token: 'EOL', line: 57, column: 21 },
  { token: '%', line: 58, column: 1 },
  { token: 'identifier', string: 'endmacro', line: 58, column: 2 },
  { token: 'EOL', line: 58, column: 10 },
  { token: 'EOL', line: 59, column: 1 },
  { token: '%', line: 60, column: 1 },
  { token: 'identifier', string: 'macro', line: 60, column: 2 },
  { token: 'identifier', string: 'store', line: 60, column: 8 },
  { token: 'EOL', line: 60, column: 40 },
  { token: 'identifier', string: 'connect', line: 61, column: 3 },
  { token: ',', line: 61, column: 11 },
  { token: 'EOL', line: 61, column: 12 },
  { token: '%', line: 62, column: 1 },
  { token: 'identifier', string: 'endmacro', line: 62, column: 2 },
  { token: 'EOL', line: 62, column: 10 },
  { token: 'EOL', line: 63, column: 1 },
  { token: '%', line: 64, column: 1 },
  { token: 'identifier', string: 'macro', line: 64, column: 2 },
  { token: 'identifier', string: 'pushconst', line: 64, column: 8 },
  { token: 'EOL', line: 64, column: 28 },
  { token: 'identifier', string: 'none', line: 65, column: 3 },
  { token: 'signal', string: 'red', line: 65, column: 11 },
  { token: 'number', string: '0', number: 0, line: 65, column: 17 },
  { token: 'signal', string: 'S', line: 65, column: 19 },
  { token: 'number', string: '1', number: 1, line: 65, column: 23 },
  { token: ',', line: 65, column: 24 },
  { token: 'signal', string: 'memw', line: 65, column: 26 },
  { token: 'EOL', line: 65, column: 32 },
  { token: 'identifier', string: 'arith', line: 66, column: 3 },
  { token: 'signal', string: 'S', line: 66, column: 11 },
  { token: ',', line: 66, column: 14 },
  { token: 'signal', string: 'OR', line: 66, column: 16 },
  { token: ',', line: 66, column: 20 },
  { token: 'number', string: '0', number: 0, line: 66, column: 22 },
  { token: ',', line: 66, column: 23 },
  { token: 'signal', string: 'red', line: 66, column: 25 },
  { token: ',', line: 66, column: 30 },
  { token: 'identifier', string: 'clear', line: 66, column: 32 },
  { token: ',', line: 66, column: 37 },
  { token: 'signal', string: 'memr', line: 66, column: 39 },
  { token: ',', line: 66, column: 45 },
  { token: 'signal', string: 'memw', line: 66, column: 47 },
  { token: 'EOL', line: 66, column: 53 },
  { token: 'identifier', string: 'arith', line: 67, column: 3 },
  { token: 'signal', string: 'S', line: 67, column: 11 },
  { token: ',', line: 67, column: 14 },
  { token: 'signal', string: 'OR', line: 67, column: 16 },
  { token: ',', line: 67, column: 20 },
  { token: 'number', string: '0', number: 0, line: 67, column: 22 },
  { token: ',', line: 67, column: 23 },
  { token: 'signal', string: 'red', line: 67, column: 25 },
  { token: ',', line: 67, column: 30 },
  { token: ':', line: 67, column: 32 },
  { token: 'number', string: '0', number: 0, line: 67, column: 33 },
  { token: ',', line: 67, column: 34 },
  { token: 'signal', string: 'memr', line: 67, column: 36 },
  { token: ',', line: 67, column: 42 },
  { token: 'signal', string: 'memw', line: 67, column: 44 },
  { token: 'EOL', line: 67, column: 50 },
  { token: 'identifier', string: 'nop', line: 68, column: 3 },
  { token: 'EOL', line: 68, column: 6 },
  { token: 'identifier', string: 'nop', line: 69, column: 3 },
  { token: 'EOL', line: 69, column: 6 },
  { token: '%', line: 70, column: 1 },
  { token: 'identifier', string: 'endmacro', line: 70, column: 2 },
  { token: 'EOL', line: 70, column: 10 },
  { token: 'EOL', line: 71, column: 1 },
  { token: '%', line: 72, column: 1 },
  { token: 'identifier', string: 'macro', line: 72, column: 2 },
  { token: 'identifier', string: 'push', line: 72, column: 8 },
  { token: 'EOL', line: 72, column: 40 },
  { token: 'identifier', string: 'none', line: 73, column: 3 },
  { token: 'signal', string: 'red', line: 73, column: 11 },
  { token: 'number', string: '0', number: 0, line: 73, column: 17 },
  { token: 'signal', string: 'S', line: 73, column: 19 },
  { token: 'number', string: '1', number: 1, line: 73, column: 23 },
  { token: ',', line: 73, column: 24 },
  { token: 'signal', string: 'memw', line: 73, column: 26 },
  { token: 'EOL', line: 73, column: 32 },
  { token: 'identifier', string: 'arith', line: 74, column: 3 },
  { token: 'signal', string: 'S', line: 74, column: 11 },
  { token: ',', line: 74, column: 14 },
  { token: 'signal', string: 'OR', line: 74, column: 16 },
  { token: ',', line: 74, column: 20 },
  { token: 'number', string: '0', number: 0, line: 74, column: 22 },
  { token: ',', line: 74, column: 25 },
  { token: 'signal', string: 'red', line: 74, column: 27 },
  { token: ',', line: 74, column: 32 },
  { token: ':', line: 74, column: 34 },
  { token: 'number', string: '1', number: 1, line: 74, column: 35 },
  { token: ',', line: 74, column: 39 },
  { token: 'signal', string: 'memr', line: 74, column: 41 },
  { token: ',', line: 74, column: 47 },
  { token: ':', line: 74, column: 49 },
  { token: 'number', string: '0', number: 0, line: 74, column: 50 },
  { token: 'EOL', line: 74, column: 51 },
  { token: 'identifier', string: 'arith', line: 75, column: 3 },
  { token: 'signal', string: 'S', line: 75, column: 11 },
  { token: ',', line: 75, column: 14 },
  { token: 'signal', string: 'OR', line: 75, column: 16 },
  { token: ',', line: 75, column: 20 },
  { token: 'number', string: '0', number: 0, line: 75, column: 22 },
  { token: ',', line: 75, column: 25 },
  { token: 'signal', string: 'red', line: 75, column: 27 },
  { token: ',', line: 75, column: 32 },
  { token: 'identifier', string: 'clear', line: 75, column: 34 },
  { token: ',', line: 75, column: 39 },
  { token: 'signal', string: 'memr', line: 75, column: 41 },
  { token: ',', line: 75, column: 47 },
  { token: 'signal', string: 'memw', line: 75, column: 49 },
  { token: 'EOL', line: 75, column: 55 },
  { token: 'identifier', string: 'nop', line: 76, column: 3 },
  { token: 'EOL', line: 76, column: 6 },
  { token: 'identifier', string: 'connect', line: 77, column: 3 },
  { token: ':', line: 77, column: 11 },
  { token: 'number', string: '0', number: 0, line: 77, column: 12 },
  { token: ',', line: 77, column: 13 },
  { token: 'signal', string: 'memw', line: 77, column: 15 },
  { token: 'EOL', line: 77, column: 21 },
  { token: 'identifier', string: 'arith', line: 78, column: 3 },
  { token: 'number', string: '0', number: 0, line: 78, column: 11 },
  { token: ',', line: 78, column: 14 },
  { token: 'signal', string: '-', line: 78, column: 16 },
  { token: ',', line: 78, column: 20 },
  { token: 'signal', string: 'S', line: 78, column: 22 },
  { token: ',', line: 78, column: 25 },
  { token: 'signal', string: 'red', line: 78, column: 27 },
  { token: ',', line: 78, column: 32 },
  { token: ',', line: 78, column: 39 },
  { token: 'signal', string: 'memr', line: 78, column: 41 },
  { token: ',', line: 78, column: 47 },
  { token: ':', line: 78, column: 49 },
  { token: 'number', string: '0', number: 0, line: 78, column: 50 },
  { token: 'EOL', line: 78, column: 51 },
  { token: '%', line: 79, column: 1 },
  { token: 'identifier', string: 'endmacro', line: 79, column: 2 },
  { token: 'EOL', line: 79, column: 10 },
  { token: 'EOL', line: 80, column: 1 },
  { token: '%', line: 81, column: 1 },
  { token: 'identifier', string: 'macro', line: 81, column: 2 },
  { token: 'identifier', string: 'pop', line: 81, column: 8 },
  { token: 'EOL', line: 81, column: 34 },
  { token: 'identifier', string: 'none', line: 82, column: 3 },
  { token: 'signal', string: 'red', line: 82, column: 11 },
  { token: 'number', string: '0', number: 0, line: 82, column: 17 },
  { token: 'signal', string: 'S', line: 82, column: 19 },
  { token: '-', line: 82, column: 23 },
  { token: 'number', string: '1', number: 1, line: 82, column: 24 },
  { token: ',', line: 82, column: 25 },
  { token: 'signal', string: 'memw', line: 82, column: 27 },
  { token: 'EOL', line: 82, column: 33 },
  { token: 'identifier', string: 'arith', line: 83, column: 3 },
  { token: 'signal', string: 'S', line: 83, column: 11 },
  { token: ',', line: 83, column: 14 },
  { token: 'signal', string: 'OR', line: 83, column: 16 },
  { token: ',', line: 83, column: 20 },
  { token: 'number', string: '0', number: 0, line: 83, column: 22 },
  { token: ',', line: 83, column: 23 },
  { token: 'signal', string: 'green', line: 83, column: 25 },
  { token: ',', line: 83, column: 32 },
  { token: 'signal', string: 'green', line: 83, column: 34 },
  { token: '-', line: 83, column: 42 },
  { token: 'number', string: '1', number: 1, line: 83, column: 43 },
  { token: ',', line: 83, column: 44 },
  { token: 'signal', string: 'memr', line: 83, column: 46 },
  { token: ',', line: 83, column: 52 },
  { token: 'signal', string: 'memq', line: 83, column: 54 },
  { token: 'EOL', line: 83, column: 60 },
  { token: 'identifier', string: 'nop', line: 84, column: 3 },
  { token: 'EOL', line: 84, column: 6 },
  { token: 'identifier', string: 'none', line: 85, column: 3 },
  { token: 'identifier', string: 'clear', line: 85, column: 11 },
  { token: ',', line: 85, column: 16 },
  { token: ':', line: 85, column: 18 },
  { token: 'number', string: '0', number: 0, line: 85, column: 19 },
  { token: 'EOL', line: 85, column: 20 },
  { token: 'identifier', string: 'connect', line: 86, column: 3 },
  { token: 'signal', string: 'memr', line: 86, column: 11 },
  { token: ',', line: 86, column: 17 },
  { token: ':', line: 86, column: 19 },
  { token: 'number', string: '0', number: 0, line: 86, column: 20 },
  { token: 'EOL', line: 86, column: 21 },
  { token: '%', line: 87, column: 1 },
  { token: 'identifier', string: 'endmacro', line: 87, column: 2 },
  { token: 'EOL', line: 87, column: 10 },
  { token: 'EOL', line: 88, column: 1 },
  { token: 'EOL', line: 89, column: 1 },
  { token: '%', line: 90, column: 1 },
  { token: 'identifier', string: 'macro', line: 90, column: 2 },
  { token: 'identifier', string: 'top', line: 90, column: 8 },
  { token: 'EOL', line: 90, column: 41 },
  { token: 'identifier', string: 'arith', line: 91, column: 3 },
  { token: 'signal', string: 'S', line: 91, column: 11 },
  { token: ',', line: 91, column: 14 },
  { token: 'signal', string: 'OR', line: 91, column: 16 },
  { token: ',', line: 91, column: 20 },
  { token: 'number', string: '0', number: 0, line: 91, column: 22 },
  { token: ',', line: 91, column: 23 },
  { token: 'signal', string: 'green', line: 91, column: 25 },
  { token: ',', line: 91, column: 32 },
  { token: 'signal', string: 'green', line: 91, column: 34 },
  { token: '-', line: 91, column: 42 },
  { token: 'number', string: '1', number: 1, line: 91, column: 43 },
  { token: '-', line: 91, column: 45 },
  { token: ':', line: 91, column: 47 },
  { token: 'number', string: '1', number: 1, line: 91, column: 48 },
  { token: ',', line: 91, column: 49 },
  { token: 'signal', string: 'memr', line: 91, column: 51 },
  { token: ',', line: 91, column: 57 },
  { token: 'signal', string: 'memq', line: 91, column: 59 },
  { token: 'EOL', line: 91, column: 65 },
  { token: 'identifier', string: 'nop', line: 92, column: 3 },
  { token: 'EOL', line: 92, column: 6 },
  { token: 'identifier', string: 'none', line: 93, column: 3 },
  { token: 'identifier', string: 'clear', line: 93, column: 11 },
  { token: ',', line: 93, column: 16 },
  { token: ':', line: 93, column: 18 },
  { token: 'number', string: '0', number: 0, line: 93, column: 19 },
  { token: 'EOL', line: 93, column: 20 },
  { token: 'identifier', string: 'connect', line: 94, column: 3 },
  { token: 'signal', string: 'memr', line: 94, column: 11 },
  { token: ',', line: 94, column: 17 },
  { token: ':', line: 94, column: 19 },
  { token: 'number', string: '0', number: 0, line: 94, column: 20 },
  { token: 'EOL', line: 94, column: 21 },
  { token: '%', line: 95, column: 1 },
  { token: 'identifier', string: 'endmacro', line: 95, column: 2 },
  { token: 'EOL', line: 95, column: 10 },
  { token: 'EOL', line: 96, column: 1 },
  { token: '%', line: 97, column: 1 },
  { token: 'identifier', string: 'macro', line: 97, column: 2 },
  { token: 'identifier', string: 'call', line: 97, column: 8 },
  { token: 'EOL', line: 97, column: 20 },
  { token: 'identifier', string: 'pushconst', line: 98, column: 3 },
  { token: 'signal', string: 'B', line: 98, column: 13 },
  { token: '-', line: 98, column: 17 },
  { token: 'identifier', string: 'ip', line: 98, column: 19 },
  { token: '-', line: 98, column: 22 },
  { token: 'number', string: '4', number: 4, line: 98, column: 24 },
  { token: 'EOL', line: 98, column: 25 },
  { token: 'identifier', string: 'jmp', line: 99, column: 3 },
  { token: ':', line: 99, column: 13 },
  { token: 'number', string: '0', number: 0, line: 99, column: 14 },
  { token: 'EOL', line: 99, column: 15 },
  { token: '%', line: 100, column: 1 },
  { token: 'identifier', string: 'endmacro', line: 100, column: 2 },
  { token: 'EOL', line: 100, column: 10 },
  { token: 'EOL', line: 101, column: 1 },
  { token: '%', line: 102, column: 1 },
  { token: 'identifier', string: 'macro', line: 102, column: 2 },
  { token: 'identifier', string: 'return', line: 102, column: 8 },
  { token: 'EOL', line: 102, column: 14 },
  { token: 'identifier', string: 'arith', line: 103, column: 3 },
  { token: 'signal', string: 'S', line: 103, column: 11 },
  { token: ',', line: 103, column: 14 },
  { token: 'signal', string: 'OR', line: 103, column: 16 },
  { token: ',', line: 103, column: 20 },
  { token: 'number', string: '0', number: 0, line: 103, column: 22 },
  { token: ',', line: 103, column: 23 },
  { token: 'signal', string: 'green', line: 103, column: 25 },
  { token: ',', line: 103, column: 32 },
  { token: 'signal', string: 'green', line: 103, column: 34 },
  { token: '-', line: 103, column: 42 },
  { token: 'number', string: '1', number: 1, line: 103, column: 43 },
  { token: ',', line: 103, column: 44 },
  { token: 'signal', string: 'memr', line: 103, column: 46 },
  { token: ',', line: 103, column: 52 },
  { token: 'signal', string: 'memq', line: 103, column: 54 },
  { token: 'EOL', line: 103, column: 60 },
  { token: 'identifier', string: 'none', line: 104, column: 3 },
  { token: 'signal', string: 'red', line: 104, column: 11 },
  { token: 'signal', string: 'S', line: 104, column: 17 },
  { token: '-', line: 104, column: 21 },
  { token: 'number', string: '1', number: 1, line: 104, column: 22 },
  { token: ',', line: 104, column: 23 },
  { token: 'signal', string: 'memw', line: 104, column: 25 },
  { token: 'EOL', line: 104, column: 31 },
  { token: 'identifier', string: 'nop', line: 105, column: 3 },
  { token: 'EOL', line: 105, column: 6 },
  { token: 'identifier', string: 'arith', line: 106, column: 3 },
  { token: 'signal', string: 'B', line: 106, column: 11 },
  { token: ',', line: 106, column: 14 },
  { token: 'signal', string: 'OR', line: 106, column: 16 },
  { token: ',', line: 106, column: 20 },
  { token: 'number', string: '0', number: 0, line: 106, column: 22 },
  { token: ',', line: 106, column: 23 },
  { token: 'signal', string: 'B', line: 106, column: 25 },
  { token: ',', line: 106, column: 28 },
  { token: 'signal', string: 'B', line: 106, column: 30 },
  { token: 'number', string: '3', number: 3, line: 106, column: 34 },
  { token: '+', line: 106, column: 36 },
  { token: 'identifier', string: 'ip', line: 106, column: 38 },
  { token: ',', line: 106, column: 40 },
  { token: 'signal', string: 'memr', line: 106, column: 42 },
  { token: ',', line: 106, column: 48 },
  { token: 'signal', string: 'jump', line: 106, column: 50 },
  { token: 'EOL', line: 106, column: 56 },
  { token: 'identifier', string: 'nop', line: 107, column: 3 },
  { token: 'EOL', line: 107, column: 6 },
  { token: 'identifier', string: 'nop', line: 108, column: 3 },
  { token: 'EOL', line: 108, column: 6 },
  { token: '%', line: 109, column: 1 },
  { token: 'identifier', string: 'endmacro', line: 109, column: 2 },
  { token: 'EOL', line: 109, column: 10 },
  { token: 'EOL', line: 110, column: 1 },
  { token: '%', line: 111, column: 1 },
  { token: 'identifier', string: 'macro', line: 111, column: 2 },
  { token: 'identifier', string: 'stack_setup', line: 111, column: 8 },
  { token: 'EOL', line: 111, column: 19 },
  { token: 'identifier', string: 'none', line: 112, column: 3 },
  { token: 'identifier', string: 'clear', line: 112, column: 11 },
  { token: '+', line: 112, column: 17 },
  { token: 'signal', string: 'red', line: 112, column: 19 },
  { token: 'identifier', string: 'sp', line: 112, column: 25 },
  { token: ',', line: 112, column: 27 },
  { token: 'signal', string: 'memw', line: 112, column: 29 },
  { token: 'EOL', line: 112, column: 35 },
  { token: 'identifier', string: 'none', line: 113, column: 3 },
  { token: 'signal', string: 'red', line: 113, column: 11 },
  { token: 'identifier', string: 'sp', line: 113, column: 17 },
  { token: 'signal', string: 'S', line: 113, column: 20 },
  { token: 'identifier', string: 'stack', line: 113, column: 24 },
  { token: ',', line: 113, column: 29 },
  { token: 'signal', string: 'memw', line: 113, column: 31 },
  { token: 'EOL', line: 113, column: 37 },
  { token: 'identifier', string: 'nop', line: 114, column: 3 },
  { token: 'EOL', line: 114, column: 6 },
  { token: 'identifier', string: 'nop', line: 115, column: 3 },
  { token: 'EOL', line: 115, column: 6 },
  { token: 'identifier', string: 'nop', line: 116, column: 3 },
  { token: 'EOL', line: 116, column: 6 },
  { token: 'identifier', string: 'nop', line: 117, column: 3 },
  { token: 'EOL', line: 117, column: 6 },
  { token: '%', line: 118, column: 1 },
  { token: 'identifier', string: 'endmacro', line: 118, column: 2 },
  { token: 'EOL', line: 118, column: 10 },
  { token: 'EOL', line: 119, column: 1 },
  { token: '%', line: 120, column: 1 },
  { token: 'identifier', string: 'macro', line: 120, column: 2 },
  { token: 'identifier', string: 'storeconst', line: 120, column: 8 },
  { token: 'EOL', line: 120, column: 47 },
  { token: 'identifier', string: 'none', line: 121, column: 3 },
  { token: 'identifier', string: 'clear', line: 121, column: 11 },
  { token: '+', line: 121, column: 17 },
  { token: 'signal', string: 'red', line: 121, column: 19 },
  { token: ':', line: 121, column: 25 },
  { token: 'number', string: '0', number: 0, line: 121, column: 26 },
  { token: ',', line: 121, column: 27 },
  { token: 'signal', string: 'memw', line: 121, column: 29 },
  { token: 'EOL', line: 121, column: 35 },
  { token: 'identifier', string: 'none', line: 122, column: 3 },
  { token: '(', line: 122, column: 11 },
  { token: 'signal', string: 'red', line: 122, column: 12 },
  { token: ':', line: 122, column: 18 },
  { token: 'number', string: '0', number: 0, line: 122, column: 19 },
  { token: ')', line: 122, column: 20 },
  { token: '+', line: 122, column: 22 },
  { token: ':', line: 122, column: 24 },
  { token: 'number', string: '1', number: 1, line: 122, column: 25 },
  { token: ',', line: 122, column: 26 },
  { token: 'signal', string: 'memw', line: 122, column: 28 },
  { token: 'EOL', line: 122, column: 34 },
  { token: '%', line: 123, column: 1 },
  { token: 'identifier', string: 'endmacro', line: 123, column: 2 },
  { token: 'EOL', line: 123, column: 10 },
  { token: 'EOL', line: 124, column: 1 },
  { token: 'EOL', line: 125, column: 48 },
  { token: '%', line: 126, column: 1 },
  { token: 'identifier', string: 'macro', line: 126, column: 2 },
  { token: 'identifier', string: 'append_m2m', line: 126, column: 8 },
  { token: 'EOL', line: 126, column: 56 },
  { token: 'identifier', string: 'none', line: 127, column: 3 },
  { token: 'signal', string: 'green', line: 127, column: 11 },
  { token: ':', line: 127, column: 19 },
  { token: 'number', string: '0', number: 0, line: 127, column: 20 },
  { token: ',', line: 127, column: 21 },
  { token: 'signal', string: 'memq', line: 127, column: 23 },
  { token: 'EOL', line: 127, column: 29 },
  { token: 'identifier', string: 'nop', line: 128, column: 3 },
  { token: 'EOL', line: 128, column: 6 },
  { token: 'identifier', string: 'nop', line: 129, column: 3 },
  { token: 'EOL', line: 129, column: 6 },
  { token: 'identifier', string: 'connect', line: 130, column: 3 },
  { token: 'signal', string: 'memr', line: 130, column: 11 },
  { token: ',', line: 130, column: 17 },
  { token: 'signal', string: 'memw', line: 130, column: 19 },
  { token: ',', line: 130, column: 25 },
  { token: 'signal', string: 'red', line: 130, column: 27 },
  { token: ':', line: 130, column: 33 },
  { token: 'number', string: '1', number: 1, line: 130, column: 34 },
  { token: 'EOL', line: 130, column: 35 },
  { token: '%', line: 131, column: 1 },
  { token: 'identifier', string: 'endmacro', line: 131, column: 2 },
  { token: 'EOL', line: 131, column: 10 },
  { token: 'EOL', line: 132, column: 1 },
  { token: '%', line: 133, column: 1 },
  { token: 'identifier', string: 'macro', line: 133, column: 2 },
  { token: 'identifier', string: 'mov_m2m', line: 133, column: 8 },
  { token: 'EOL', line: 133, column: 53 },
  { token: 'identifier', string: 'none', line: 134, column: 3 },
  { token: 'signal', string: 'green', line: 134, column: 11 },
  { token: ':', line: 134, column: 19 },
  { token: 'number', string: '0', number: 0, line: 134, column: 20 },
  { token: ',', line: 134, column: 21 },
  { token: 'signal', string: 'memq', line: 134, column: 23 },
  { token: 'EOL', line: 134, column: 29 },
  { token: 'identifier', string: 'none', line: 135, column: 3 },
  { token: 'identifier', string: 'clear', line: 135, column: 11 },
  { token: '+', line: 135, column: 17 },
  { token: 'signal', string: 'red', line: 135, column: 19 },
  { token: ':', line: 135, column: 25 },
  { token: 'number', string: '1', number: 1, line: 135, column: 26 },
  { token: ',', line: 135, column: 27 },
  { token: 'signal', string: 'memw', line: 135, column: 29 },
  { token: 'EOL', line: 135, column: 35 },
  { token: 'identifier', string: 'nop', line: 136, column: 3 },
  { token: 'EOL', line: 136, column: 6 },
  { token: 'identifier', string: 'connect', line: 137, column: 3 },
  { token: 'signal', string: 'memr', line: 137, column: 11 },
  { token: ',', line: 137, column: 17 },
  { token: 'signal', string: 'memw', line: 137, column: 19 },
  { token: ',', line: 137, column: 25 },
  { token: 'signal', string: 'red', line: 137, column: 27 },
  { token: ':', line: 137, column: 33 },
  { token: 'number', string: '1', number: 1, line: 137, column: 34 },
  { token: 'EOL', line: 137, column: 35 },
  { token: '%', line: 138, column: 1 },
  { token: 'identifier', string: 'endmacro', line: 138, column: 2 },
  { token: 'EOL', line: 138, column: 10 },
  { token: 'EOL', line: 139, column: 1 },
  { token: ':', line: 140, column: 1 },
  { token: 'identifier', string: 'init', line: 140, column: 2 },
  { token: 'EOL', line: 140, column: 6 },
  { token: 'identifier', string: 'stack_setup', line: 141, column: 3 },
  { token: 'EOL', line: 141, column: 14 },
  { token: ':', line: 142, column: 1 },
  { token: 'identifier', string: 'main', line: 142, column: 2 },
  { token: 'EOL', line: 142, column: 6 },
  { token: 'identifier', string: 'set', line: 143, column: 3 },
  { token: 'signal', string: 'V', line: 143, column: 15 },
  { token: 'number', string: '5', number: 5, line: 143, column: 19 },
  { token: ',', line: 143, column: 20 },
  { token: 'signal', string: 'ic', line: 143, column: 22 },
  { token: 'number', string: '1', number: 1, line: 143, column: 27 },
  { token: 'EOL', line: 143, column: 28 },
  { token: 'identifier', string: 'call', line: 144, column: 3 },
  { token: 'identifier', string: 'fibonacci', line: 144, column: 15 },
  { token: 'EOL', line: 144, column: 24 },
  { token: 'identifier', string: 'stop', line: 145, column: 3 },
  { token: 'EOL', line: 145, column: 7 },
  { token: 'EOL', line: 146, column: 1 },
  { token: ':', line: 147, column: 1 },
  { token: 'identifier', string: 'fibonacci', line: 147, column: 2 },
  { token: 'EOL', line: 147, column: 11 },
  { token: 'identifier', string: 'branch', line: 148, column: 3 },
  { token: 'identifier', string: 'fib_ret', line: 148, column: 15 },
  { token: ',', line: 148, column: 22 },
  { token: 'signal', string: 'V', line: 148, column: 24 },
  { token: ',', line: 148, column: 27 },
  { token: 'signal', string: '≤', line: 148, column: 29 },
  { token: ',', line: 148, column: 32 },
  { token: 'number', string: '1', number: 1, line: 148, column: 34 },
  { token: ',', line: 148, column: 35 },
  { token: 'signal', string: 'ic', line: 148, column: 37 },
  { token: 'number', string: '1', number: 1, line: 148, column: 42 },
  { token: 'EOL', line: 148, column: 43 },
  { token: 'EOL', line: 149, column: 1 },
  { token: 'identifier', string: 'push', line: 150, column: 3 },
  { token: 'signal', string: 'ic', line: 150, column: 15 },
  { token: 'number', string: '1', number: 1, line: 150, column: 20 },
  { token: 'EOL', line: 150, column: 21 },
  { token: 'identifier', string: 'none', line: 151, column: 3 },
  { token: 'signal', string: 'V', line: 151, column: 15 },
  { token: '-', line: 151, column: 19 },
  { token: 'number', string: '1', number: 1, line: 151, column: 20 },
  { token: ',', line: 151, column: 21 },
  { token: 'signal', string: 'ic', line: 151, column: 23 },
  { token: 'number', string: '1', number: 1, line: 151, column: 28 },
  { token: 'EOL', line: 151, column: 29 },
  { token: 'identifier', string: 'call', line: 152, column: 3 },
  { token: 'identifier', string: 'fibonacci', line: 152, column: 15 },
  { token: 'EOL', line: 152, column: 24 },
  { token: 'identifier', string: 'pop', line: 153, column: 3 },
  { token: 'signal', string: 'ic', line: 153, column: 15 },
  { token: 'number', string: '1', number: 1, line: 153, column: 20 },
  { token: 'EOL', line: 153, column: 21 },
  { token: 'EOL', line: 154, column: 1 },
  { token: 'identifier', string: 'push', line: 155, column: 3 },
  { token: 'signal', string: 'ic', line: 155, column: 15 },
  { token: 'number', string: '0', number: 0, line: 155, column: 20 },
  { token: 'EOL', line: 155, column: 21 },
  { token: 'identifier', string: 'none', line: 156, column: 3 },
  { token: 'signal', string: 'V', line: 156, column: 15 },
  { token: '-', line: 156, column: 19 },
  { token: 'number', string: '2', number: 2, line: 156, column: 20 },
  { token: ',', line: 156, column: 21 },
  { token: 'signal', string: 'ic', line: 156, column: 23 },
  { token: 'number', string: '1', number: 1, line: 156, column: 28 },
  { token: 'EOL', line: 156, column: 29 },
  { token: 'identifier', string: 'call', line: 157, column: 3 },
  { token: 'identifier', string: 'fibonacci', line: 157, column: 15 },
  { token: 'EOL', line: 157, column: 24 },
  { token: 'identifier', string: 'pop', line: 158, column: 3 },
  { token: 'signal', string: 'ic', line: 158, column: 15 },
  { token: 'number', string: '1', number: 1, line: 158, column: 20 },
  { token: 'EOL', line: 158, column: 21 },
  { token: 'EOL', line: 159, column: 1 },
  { token: 'identifier', string: 'connect', line: 160, column: 3 },
  { token: 'signal', string: 'ic', line: 160, column: 15 },
  { token: 'number', string: '1', number: 1, line: 160, column: 20 },
  { token: ',', line: 160, column: 21 },
  { token: 'signal', string: 'ic', line: 160, column: 23 },
  { token: 'number', string: '0', number: 0, line: 160, column: 28 },
  { token: 'EOL', line: 160, column: 29 },
  { token: 'identifier', string: 'return', line: 161, column: 3 },
  { token: 'EOL', line: 161, column: 9 },
  { token: ':', line: 162, column: 1 },
  { token: 'identifier', string: 'fib_ret', line: 162, column: 2 },
  { token: 'EOL', line: 162, column: 9 },
  { token: 'identifier', string: 'mov', line: 163, column: 3 },
  { token: 'signal', string: 'ic', line: 163, column: 15 },
  { token: 'number', string: '1', number: 1, line: 163, column: 20 },
  { token: ',', line: 163, column: 21 },
  { token: 'signal', string: 'ic', line: 163, column: 23 },
  { token: 'number', string: '0', number: 0, line: 163, column: 28 },
  { token: 'EOL', line: 163, column: 29 },
  { token: 'identifier', string: 'return', line: 164, column: 3 },
  { token: 'EOL', line: 164, column: 9 },
  { token: 'EOL', line: 165, column: 1 }
]